name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fmt
        run: test `go fmt ./... | wc -l` -eq 0

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
